- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - freezer-tempest-basic
        - freezer-tempest-client
        - freezer-tempest-scheduler
        - freezer-tempest-agent
        - freezer-tempest-basic-sql
        - freezer-tempest-basic-ussuri
        - freezer-tempest-basic-train
        - freezer-tempest-basic-stein

    gate:
      queue: freezer
      jobs:
        - freezer-tempest-basic
        - freezer-tempest-client
        - freezer-tempest-scheduler
        - freezer-tempest-agent
        - freezer-tempest-basic-sql

- job:
    name: freezer-tempest-basic
    parent: devstack-tempest
    # TODO(gmann): Remove the below nodeset setting to Bionic once
    # bug https://bugs.launchpad.net/freezer/+bug/1896648 is fixed.
    # Once nodeset is removed form here then devstack-tempest job
    # will automatically run this job on Ubuntu Focal nodeset from
    # Victoria gate onwards.
    nodeset: openstack-single-node-bionic
    timeout: 7200
    required-projects:
      - openstack/python-openstackclient
      - openstack/swift
      - openstack/python-freezerclient
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-tempest-plugin
      - openstack/tempest
    vars:
      devstack_plugins:
        freezer-api: https://opendev.org/openstack/freezer-api
        freezer: https://opendev.org/openstack/freezer
      devstack_services:
        tls-proxy: false
        freezer-api: true
        tempest: true
        swift: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      tempest_plugins:
        - freezer-tempest-plugin
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezer_api.)'
      tox_envlist: 'all'
      zuul_copy_output:
        /etc/hosts: logs

- job:
    name: freezer-tempest-client
    parent: freezer-tempest-basic
    voting: true
    vars:
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezerclient.)'

- job:
    name: freezer-tempest-scheduler
    parent: freezer-tempest-basic
    voting: true
    vars:
      tempest_test_regex: '^(freezer_tempest_plugin.tests.scheduler.)'

- job:
    name: freezer-tempest-agent
    parent: freezer-tempest-basic
    voting: true
    vars:
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezer.agent.)'

- job:
    name: freezer-tempest-basic-sql
    parent: freezer-tempest-basic
    vars:
      devstack_localrc:
        FREEZER_BACKEND: 'sqlalchemy'

- job:
    name: freezer-tempest-basic-ussuri
    parent: freezer-tempest-basic
    nodeset: openstack-single-node-bionic
    override-checkout: stable/ussuri

- job:
    name: freezer-tempest-basic-train
    parent: freezer-tempest-basic
    override-checkout: stable/train
    nodeset: openstack-single-node-bionic
    vars:
      devstack_localrc:
        USE_PYTHON3: True

- job:
    name: freezer-tempest-basic-stein
    parent: freezer-tempest-basic
    nodeset: openstack-single-node-bionic
    override-checkout: stable/stein
    vars:
      devstack_localrc:
        USE_PYTHON3: True
