- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - freezer-tempest-basic
        - freezer-tempest-client
        - freezer-tempest-scheduler
        - freezer-tempest-agent
        - freezer-tempest-basic-sql

    gate:
      queue: freezer
      jobs:
        - freezer-tempest-basic
        - freezer-tempest-client
        - freezer-tempest-scheduler
        - freezer-tempest-agent
        - freezer-tempest-basic-sql

- job:
    name: freezer-tempest-basic
    parent: devstack-tempest
    timeout: 7200
    required-projects:
      - openstack/devstack-gate
      - openstack/python-openstackclient
      - openstack/swift
      - openstack/python-freezerclient
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-tempest-plugin
      - openstack/tempest
    vars:
      devstack_plugins:
        freezer-api: https://opendev.org/openstack/freezer-api
        freezer: https://opendev.org/openstack/freezer
      devstack_services:
        tls-proxy: false
        freezer-api: true
        tempest: true
        swift: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      devstack_localrc:
        TEMPEST_PLUGINS: '/opt/stack/freezer-tempest-plugin'
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezer_api.)'
      tox_envlist: 'all'
      tox_environment:
        PYTHONUNBUFFERED: 'true'
      zuul_copy_output:
        /etc/hosts: logs

- job:
    name: freezer-tempest-client
    parent: freezer-tempest-basic
    voting: true
    vars:
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezerclient.)'

- job:
    name: freezer-tempest-scheduler
    parent: freezer-tempest-basic
    voting: true
    vars:
      tempest_test_regex: '^(freezer_tempest_plugin.tests.scheduler.)'

- job:
    name: freezer-tempest-agent
    parent: freezer-tempest-basic
    voting: true
    vars:
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezer.agent.)'

- job:
    name: freezer-tempest-basic-sql
    parent: devstack-tempest
    timeout: 7200
    required-projects:
      - openstack/devstack-gate
      - openstack/python-openstackclient
      - openstack/python-freezerclient
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-tempest-plugin
      - openstack/tempest
    vars:
      devstack_plugins:
        freezer-api: https://opendev.org/openstack/freezer-api
        freezer: https://opendev.org/openstack/freezer
      devstack_services:
        tls-proxy: false
        freezer-api: true
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      devstack_localrc:
        FREEZER_BACKEND: 'sqlalchemy'
        TEMPEST_PLUGINS: '/opt/stack/freezer-tempest-plugin'
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezer_api)'
      tox_envlist: all
      tox_environment:
        PYTHONUNBUFFERED: 'true'
      zuul_copy_output:
        /etc/hosts: logs

